// File generated by FlutterFire CLI.
// Contains Firebase configuration for the app.
// You need to replace this file with the one generated from the Firebase console.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Replace with your Firebase configuration
    // This is a placeholder - you need to run flutterfire configure or add your own config
    return const FirebaseOptions(
      apiKey: "AIzaSyBsz9ETDtiV78gTBqAEqnBrzM8TG4-_Cvs",
      appId: "1:82312586184:android:64df90971191d4525756fd",
      messagingSenderId: "82312586184",
      projectId: "todo-app-57b9e",
    );
  }
} 